CHANGELOG.md
lib/scimitar/version.rb
scimitar.gemspec

RubyGems won't let me repush 1.0.0 and yanking is a bad look, so I'd rather have the mistake out in the open and just do a patch version update.
Without this, you've got RDoc links & RIP Global's home page, but no GitHub link visible within RubyGems.

Add source code link to gemspec file

---

app/models/scimitar/schema/address.rb

**What this does:**
Adds a primary _boolean_ attribute to `Schema::Address`. There is a note in the [Specification versus implementation](https://github.com/RIPAGlobal/scimitar#specification-versus-implementation) section regarding the the use of `primary` in several complex types on a User. 
**Why?**
Okta sends a `primary` attribute with the addresses list. This resolves the resulting _unknown attribute_ error.

Adds the primary attribute to the Address schema

---

app/models/scimitar/lists/query_parser.rb

This commit:
- adds some detail about the nature of the error to a few sites that
raise `Scimitar:FilterError`s. This is limited to errors that arise
due to invalid input
Why?
- This should allow for easier debugging when these errors are raised

Add detail to some FilterErrors

---

README.md
app/models/scimitar/engine_configuration.rb
app/models/scimitar/schema/vdtp.rb
config/initializers/scimitar.rb

**What this does:**
Provides a Engine configuration option to require (or not) the `value` filed for complex _vdtp_ types.
**Why?**
Some providers are sending `NULL` values when syncing lists such as phone numbers. Although I agree with the Readme statement:
> there's no point being sent (say) an e-mail section which has entries that don't provide the e-mail address!
Unfortunately, if an identity provider is sending `NULL` rather than omitting the result from a list this provides a way to work around that. We should be using Model validations anyway.

Adds configuration option to not require value attributes.

---

app/models/scimitar/resources/mixin.rb
spec/models/scimitar/resources/mixin_spec.rb

This PR is to fix a particular request from Okta, but is likely more widely useful. We came across this when Okta attempts to deactivate a User. They use a `PATCH` request like so:
```
curl --location --request PATCH '$SCIM_URL/Users/$USER_ID' \
--header 'Content-Type:  application/scim+json' \
--header 'Authorization: Bearer $SCIM_TOKEN' \
--data-raw '   {
"schemas":
["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
"Operations":[{
"op":"replace",
"value": {
"active": false
}
}]
}    '
```
This wasn't working as intended, however a request like this _was_ working:
```
curl --location --request PATCH '$SCIM_URL/Users/$USER_ID' \
--header 'Content-Type:  application/scim+json' \
--header 'Authorization: Bearer $SCIM_TOKEN' \
--data-raw '   {
"schemas": …
```

Fix patch replace when path is omitted

---

CHANGELOG.md
Gemfile.lock
README.md
app/models/scimitar/lists/query_parser.rb
lib/scimitar/version.rb
spec/apps/dummy/app/models/mock_user.rb
spec/apps/dummy/db/migrate/20230109012729_add_timestamps_to_mock_user.rb
spec/apps/dummy/db/schema.rb
spec/models/scimitar/lists/query_parser_spec.rb
spec/models/scimitar/schema/attribute_spec.rb
spec/requests/active_record_backed_resources_controller_spec.rb

**Builds on #38 and cannot be merged before it.**
Resolves #36, with the net cast a little wider to allow for a few particular examples of `caseExact` set to `true` in https://www.rfc-editor.org/rfc/rfc7643#section-3.1.

Allow filtering by "id" "externalId" and "meta."

---

CHANGELOG.md
Gemfile.lock
app/controllers/scimitar/active_record_backed_resources_controller.rb
lib/scimitar/version.rb
spec/apps/dummy/app/controllers/mock_groups_controller.rb
spec/apps/dummy/app/models/mock_group.rb
spec/apps/dummy/app/models/mock_user.rb
spec/apps/dummy/config/routes.rb
spec/apps/dummy/db/migrate/20210304014602_create_mock_users.rb
spec/apps/dummy/db/migrate/20210308044214_create_join_table_mock_groups_mock_users.rb
spec/apps/dummy/db/migrate/20230109012729_add_timestamps_to_mock_user.rb
spec/apps/dummy/db/schema.rb
spec/models/scimitar/lists/query_parser_spec.rb
spec/models/scimitar/resources/mixin_spec.rb
spec/requests/active_record_backed_resources_controller_spec.rb

Address https://github.com/RIPAGlobal/scimitar/issues/35. Declaring primary key in the ActiveRecord model would solve most of the problems described, but v2.2.0 did introduce a default order clause that would trip up a model with a different primary key name; this is now fixed. In any case, it may be possible to avoid declaring the primary key override in the model entirely if using Scimitar v2.3.0, should that be your wish. This is in effect an edge case new feature, which is why the gem's minor version has been bumped up.
Maintenance `bundle update` included, which amongst other things pulls in "officially supports Ruby 3.2.0" Doggo v1.3 (only relevant for developers running the gem's tests).
Hide white space while viewing changes for a cleaner diff.

Address issue #35, with caveats noted in issue #35 discussion

---

app/models/scimitar/resources/mixin.rb
spec/apps/dummy/config/routes.rb
spec/models/scimitar/resources/mixin_spec.rb
spec/requests/active_record_backed_resources_controller_spec.rb

Tolerates the Microsoft form of patch-remove payload (in a fairly gene…ric way) and the Salesforce payload (as a limited special case) - addresses https://github.com/RIPAGlobal/scimitar/issues/43.
The [RFC way to remove a user from a group](https://www.rfc-editor.org/rfc/rfc7644#section-3.5.2.2) is via a filter:
```json
{ "schemas":
["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
"Operations": [
{
"op":"remove",
"path":
"members[value eq\"2819c223...919d-413861904646\"]"
}
]
}
```
...with [_arguably_ forms of payload that attempt to specify the user(s) to remove in the `value` parameter](https://github.com/simpleidserver/SimpleIdServer/issues/164#issuecomment-871456758) rather than a filter in `path`, having that `value` ignored with the `path` of just `members` then matching the RFC's …

Handle possibly non-compliant PATCH payloads (for real-world use cases)

---

app/controllers/scimitar/application_controller.rb
spec/requests/application_controller_spec.rb

We encountered a problem using Microsoft Azure AD and traced it down to Microsoft sending `application/scim+json; charset=utf-8` in the `CONTENT_TYPE` header when calling `POST /Users`.
Since the CONTENT_TYPE header can contain more than just the Mime-Type scimitar should use `start_with?` instead of `==`. This PR changes that.
PS: I'm not sure if stripping the charset away from the `CONTENT_TPYE` header is wise. I just added that because the tests looked "more correct" to me first sight. If you know more or have objections just drop me a line.

Handle CONTENT_TYPE header containing charset correctly

---

CHANGELOG.md
Gemfile.lock
app/controllers/scimitar/application_controller.rb
lib/scimitar/version.rb
spec/requests/application_controller_spec.rb

Backport v2.4.2 features - see #51, noting the addition of a check for an empty media type shown up by tests.

Backport v2.4.2 features

---

config/initializers/scimitar.rb

```
[Sessions] Sessions won't be captured without a valid release
DEPRECATION WARNING: Initialization autoloaded the constants Scimitar::ServiceProviderConfiguration, Scimitar::Supportable, Scimitar::Filter, Scimitar::Meta, Scimitar::AuthenticationScheme, and Scimitar::EngineConfiguration.
Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.
Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload Scimitar::ServiceProviderConfiguration, for example,
the expected changes won't be reflected in that stale Class object.
These autoloaded constants have been unloaded.
Please, check the "Autoloading and Reloading Constants" guide for …
```

Fix warning messages for Rails 6 and Zeitwerk

---

CHANGELOG.md
Gemfile.lock
app/models/scimitar/engine_configuration.rb
app/models/scimitar/service_provider_configuration.rb
config/initializers/scimitar.rb
lib/scimitar.rb
lib/scimitar/version.rb
spec/apps/dummy/config/initializers/scimitar.rb
spec/controllers/scimitar/application_controller_spec.rb

Support #54 but with backwards compatibility. Applications that don't use `to_prepare` will no longer have their configuration updated by Scimitar's defaults via its own `to_prepare` block.

Backwards-compatible modifications to support #54

---

README.md
app/models/scimitar/resources/base.rb
spec/apps/dummy/app/models/mock_user.rb
spec/models/scimitar/resources/base_spec.rb

My goal is to be able to add groups to users, the same way we can add users to groups. Since that's not allowed by the SCIM default User schema, I have an extension type like this:
```ruby
module Scim
class UserExtension < Scimitar::Schema::Base
def initialize(_options = {})
super(
name: "ExtendedUser",
description: "Auth Service extension for a User",
id: self.class.id,
scim_attributes: self.class.scim_attributes
)
end
def self.id
"urn:ietf:params:scim:schemas:extension:authservice:2.0:User"
end
def self.scim_attributes
[
Scimitar::Schema::Attribute.new(name: "userGroups", multiValued: true, complexType: Scimitar::ComplexTypes::ReferenceGroup, mutability: "writeOnly"),
]
end
end
end
```
But I'm currently not able to use this type like this in my project:
```ruby
it "creates a user with …
```

Allow writable complex types in extensions

---

app/models/scimitar/lists/query_parser.rb
spec/models/scimitar/lists/query_parser_spec.rb

Allow combined logical groups. I.e.:
```
filter=(name.givenName eq "Jane" OR name.givenName eq "Jaden") and (name.familyName co "avi" or name.familyName ew "ith")
```
Without this fix, the parser assumes it can't process a logical operation at the end of a group.
With this fix it produces the following SQL:
```sql
SELECT "mock_users".*
FROM "mock_users"
WHERE ("mock_users"."first_name" ILIKE 'Jane' OR "mock_users"."first_name" ILIKE 'Jaden')
AND ("mock_users"."last_name" ILIKE '%avi%' OR "mock_users"."last_name" ILIKE '%ith')
```

Allow combined logical groups to generate working queries

---

app/models/scimitar/resources/mixin.rb
spec/models/scimitar/resources/mixin_spec.rb

Throws a comprehensible error when missing `operations` in a PatchOp

Comprehensible error when PatchOp is missing operations

---

README.md
app/models/scimitar/lists/query_parser.rb
app/models/scimitar/resources/mixin.rb
spec/apps/dummy/app/models/mock_user.rb
spec/models/scimitar/lists/query_parser_spec.rb

Allow using external columns for complex joins. In the bellow example we're able to query the user membership within a group:
```ruby
class User < ApplicationRecord
has_and_belongs_to_many :groups
def self.scim_queryable_attributes
return {
'groups'       => { column: Group.arel_table[:id] },
'groups.value' => { column: Group.arel_table[:id] },
}
end
end
```
Then:
```ruby
class UsersController < Scimitar::ActiveRecordBackedResourcesController
def storage_class
::User
end
def storage_scope
::User.left_joins(:groups)
end
end
```

Allow complex queries with table joins

---

.github/workflows/main.yml
CHANGELOG.md
Gemfile.lock
README.md
app/controllers/scimitar/application_controller.rb
app/models/scimitar/lists/query_parser.rb
app/models/scimitar/resources/base.rb
app/models/scimitar/resources/mixin.rb
lib/scimitar/version.rb
spec/apps/dummy/app/models/mock_user.rb
spec/apps/dummy/config/routes.rb
spec/models/scimitar/lists/query_parser_spec.rb
spec/models/scimitar/resources/base_spec.rb
spec/models/scimitar/resources/mixin_spec.rb

Back-ports changes from #61, #62, #65 and #66 into V1, to be released as v1.6.0. Thanks @xjunior!

Version 1.6.0

---

app/models/scimitar/schema/attribute.rb
spec/models/scimitar/schema/attribute_spec.rb

Hi @pond,
This one fixes an issue where a multi-valued string attribute did not accept an array of strings because validation of simple types didn't account for the `multiValued` property. We use such an attribute in a custom schema extension, and it should be possible within the specification. (There are even some standard attributes that are arrays of simple types, for instance `referenceTypes`.)
Thanks again,
Sjoerd

Multi-valued simple type validation

---

app/controllers/scimitar/active_record_backed_resources_controller.rb
spec/apps/dummy/app/controllers/custom_save_mock_users_controller.rb
spec/apps/dummy/config/routes.rb
spec/requests/active_record_backed_resources_controller_spec.rb

Hi @pond, it's me [again](https://github.com/RIPAGlobal/scimitar/pull/71).
This time I extended `ActiveRecordBackedResourcesController#save!` to accept a block, so that subclasses may override the default `record.save!` call with their own saving logic, without having to reimplement the rescue clause for handling uniqueness errors. Also, it aligns nicely with the destroy action, which already accepts a block for a very similar reasons.
In our case we would like a service object to save the record and do some other stuff, because we do not want to employ AR callbacks for that other stuff. With these changes it can look like this:
```rb
def save!(record)
super do
Services::ManagedUser::Save.new(record).call
end
end
```
This will be helpful in many situations. But sometimes it's not enough. …

Add option to pass block to controller's #save!

---

README.md
app/controllers/scimitar/schemas_controller.rb
app/models/scimitar/schema/base.rb
config/initializers/scimitar.rb
spec/apps/dummy/config/initializers/scimitar.rb
spec/controllers/scimitar/resource_types_controller_spec.rb
spec/controllers/scimitar/schemas_controller_spec.rb

Makes schema location URLs be generated in the controller. This way required keyword arguments for the URL helper are automatically revolved from the current path parameters. This solves an issues when Scimitar's routes are mounted inside a namespace with variable parameters. E.g. in our multitenant environment we have:
```rb
namespace :scim do
namespace :v2 do
resources :organizations, only: [] do
mount Scimitar::Engine, at: '/'
end
end
end
```
In this case `#scim_schemas_url` requires the `:organization_id` key, which is omitted when the URL is generated in `Schema::Base#as_json`. This causes an error. Using the controller's URL helper fixes this.
Additionally, the controller's URL helpers can be overridden in a simple(r) manner, making Scimitar a bit more extensible. I have utilized …

Generate schema location urls in controller

---

app/models/scimitar/resources/base.rb
spec/apps/dummy/app/models/mock_user.rb
spec/apps/dummy/db/migrate/20210304014602_create_mock_users.rb
spec/apps/dummy/db/schema.rb
spec/models/scimitar/resources/base_spec.rb
spec/models/scimitar/resources/mixin_spec.rb

Implements solution broadly as suggested in https://github.com/RIPAGlobal/scimitar/issues/56, but I need to seek clarification on https://github.com/RIPAGlobal/scimitar/issues/56#issuecomment-1590153772 as I'm not sure that amendment is necessary.

Implement solution to issue #56, as suggested therein

---

CHANGELOG.md
Gemfile.lock
app/controllers/scimitar/application_controller.rb
lib/scimitar/version.rb
spec/controllers/scimitar/application_controller_spec.rb
spec/requests/active_record_backed_resources_controller_spec.rb

Addresses https://github.com/RIPAGlobal/scimitar/issues/59; for details, see `CHANGELOG.md` diff.

Better response headers

---

app/models/scimitar/resources/mixin.rb
bin/console
lib/scimitar.rb
lib/scimitar/support/utilities.rb
spec/models/scimitar/resources/mixin_spec.rb

Hey @pond
Bit of a mouthful and I'm really just throwing spaghetti at the wall at this point to see if I'm barking up the right tree.
Microsoft's SCIM Validator strikes again. This time they're failing us on path-less replace operations not updating attributes when those attributes are in dotpath notation.
An example of a request is below:
```
PATCH https://app.colloquial.io/scim_v2/Users/326 1.1
Host: app.colloquial.io
Content-Type: application/scim+json; charset=utf-8
{
"Operations": [
{
"op": "replace",
"path": "emails[type eq \"work\"].value",
"value": "trystan@bradtkekutch.us"
},
{
"op": "replace",
"value": {
"userName": "lucienne_durgan@wiza.biz",
"name.givenName": "Keith",
"name.familyName": "Stella",
}
}
],
"schemas": [
"urn:ietf:params:scim:api:messages:2.0:PatchOp"
]
}
```
In …

Allow specifying of nested values in dotpath notation for path-less replace operations

---

README.md
app/controllers/scimitar/active_record_backed_resources_controller.rb
app/models/scimitar/resource_invalid_error.rb
spec/requests/active_record_backed_resources_controller_spec.rb

Implement suggestion from #58, with test coverage.

Implement suggestion from #58, with test coverage

---

app/models/scimitar/complex_types/address.rb
spec/models/scimitar/complex_types/address_spec.rb

In issue #87, it's pointed out that the Address complex type has a default `type` of `work`, which is unusual; such defaults were removed from other types in https://github.com/RIPAGlobal/scimitar/commit/19bab37ac846d35eee943ab20fb563cdaa107a8a.
This PR removes the default, though we must exercise caution when releasing a version of Scimitar with the change included as it _might_ be a breaking change for some clients.
(The release strategy is _probably_ still to call it 2.7.0 as it's not clear if this would break anyone, but warn in the change log - _hopefully_ that's sufficient.).

Remove default type from 'address'

---

app/models/scimitar/resources/base.rb
spec/models/scimitar/resources/base_spec.rb

👋 @pond,
Initialising a resources with `nil` for a non-required multi valued complex type attribute resulted in a NoMethodError (nil#map). This PR fixes that.

Account for nil for non-required complex type attributes

---

README.md

`remove skip_before_action :verify_authenticity_token`
It not need actually, it's an error if this line is present

Remove verify_authenticity_token from  README.md

---

README.md
app/controllers/scimitar/active_record_backed_resources_controller.rb
app/controllers/scimitar/resource_types_controller.rb
app/controllers/scimitar/resources_controller.rb
app/controllers/scimitar/schemas_controller.rb
app/controllers/scimitar/service_provider_configurations_controller.rb
lib/scimitar/engine.rb

Hey thanks for the work on this gem. I saw the note on wrapping the initializer in `Rails.application.config.to_prepare` and thought I would fix that. I'm not sure how open you guys are to PRs.
* Autoload once the app/controllers and app/models directories to prevent the uninitialized constants error.
* Removed `require_dependency` since it's obsolete and not needed with autoloading. 
* Removed the note in the readme about Rails 7 NameError.

Configure load paths of controllers and models

---

app/controllers/scimitar/active_record_backed_resources_controller.rb
app/models/scimitar/resources/mixin.rb
spec/models/scimitar/resources/mixin_spec.rb
spec/requests/active_record_backed_resources_controller_spec.rb

- Remove nil attributes from response
- Allow to selectively serialize attributes with to_scim
- Request specific attributes through ActiveRecordBackedResourcesController
Closes https://github.com/RIPAGlobal/scimitar/issues/89

Allow requesting specific attributes

---

app/models/scimitar/lists/query_parser.rb
spec/apps/dummy/app/models/mock_user.rb
spec/apps/dummy/config/initializers/scimitar.rb
spec/models/scimitar/lists/query_parser_spec.rb
spec/models/scimitar/resources/mixin_spec.rb

fix: allow attribute names starting with operator chars to be filtered

---

app/controllers/scimitar/active_record_backed_resources_controller.rb
app/models/scimitar/resources/mixin.rb
spec/models/scimitar/resources/mixin_spec.rb
spec/requests/active_record_backed_resources_controller_spec.rb

This is derived from #102 with:
* Some minor commentary fixes, including some drive-bys from when I was reviewing existing docs as part of understanding #102 and wider context
* A change in #102's blanket removal of `nil` values. There's a small chance that some existing Scimitar clients might be relying on "key is present, but value is `nil`" in returned data, so `nil` items are now only stripped out if an include-attributes list is included; otherwise, `nil` handling behaviour is unchanged.
Many thanks to @xjunior for this work.

Allow requesting specific attributes (derived from #102)

---

app/models/scimitar/lists/query_parser.rb
spec/models/scimitar/lists/query_parser_spec.rb
spec/requests/active_record_backed_resources_controller_spec.rb

Handle bad Microsoft filters in GET request (see #115)

---

Gemfile
README.md
app/controllers/scimitar/schemas_controller.rb
lib/scimitar/engine.rb
scimitar.gemspec
spec/controllers/scimitar/schemas_controller_spec.rb
spec/models/scimitar/lists/query_parser_spec.rb
spec/requests/engine_spec.rb
spec/spec_helper.rb

* Fixes https://github.com/RIPAGlobal/scimitar/issues/117
* Implements https://github.com/RIPAGlobal/scimitar/issues/118
* Drive-by `README.md` updates that were overlooked after some prior enhancements
* Drive-by update to use standard Ruby debugger instead of `byebug` during development

Fix "/Schemas" endpoint; configurable default resources

---

README.md
app/models/scimitar/resources/base.rb
lib/scimitar/support/utilities.rb
spec/apps/dummy/app/models/mock_user.rb
spec/apps/dummy/config/initializers/scimitar.rb
spec/apps/dummy/db/migrate/20210304014602_create_mock_users.rb
spec/apps/dummy/db/schema.rb
spec/controllers/scimitar/schemas_controller_spec.rb
spec/models/scimitar/resources/base_spec.rb
spec/models/scimitar/resources/mixin_spec.rb
spec/requests/active_record_backed_resources_controller_spec.rb
spec/requests/engine_spec.rb

In https://github.com/RIPAGlobal/scimitar/issues/122 problems are encountered with extension schema. This led to discovery of various shortcomings that this PR addresses (while acknowledging that there may yet be more things to fix).
* While `PATCH` handling had become more robust in recent Scimitar versions, `POST` handling had not kept up; handling was simplistic and case-sensitive. Both `"urn:schema:id": { "attr": "value" }` and potential `"urn:schema:id:attr": "value"` forms are now supported, case-insensitive.
* `PATCH` handling tripped up when multiple extension schema were in use for the same resource; this is fixed (and with `POST` now calling down to the same utility method to assist with schema ID handling, both benefit from that).
Most of the arising change set ends up in the …

Various fixes for extension schema

---

app/controllers/scimitar/schemas_controller.rb
app/models/scimitar/engine_configuration.rb
app/models/scimitar/resources/mixin.rb
config/initializers/scimitar.rb
spec/apps/dummy/app/models/mock_user.rb
spec/controllers/scimitar/schemas_controller_spec.rb
spec/models/scimitar/resources/base_spec.rb
spec/models/scimitar/resources/base_validation_spec.rb
spec/requests/engine_spec.rb

Address #119 with opt-in configuration.
Reviewing by starting with the diff of `config/initializers/scimitar.rb` is recommended, as this explains the new configuration option and, with that, the controller code which uses it will obviously make more sense.
Hiding white space changes will reduce diff noise in the tests, where a chunk of code got indented into a new `context`.

Schema-attribute-to-mapped-attribute matching for 'Schemas' endpoint

---

CHANGELOG.md
README.md
lib/scimitar/engine.rb
spec/requests/engine_spec.rb

Address https://github.com/RIPAGlobal/scimitar/pull/133#discussion_r1664897066.

Use more idiomatic calling form

---

app/controllers/scimitar/resource_types_controller.rb
spec/controllers/scimitar/resource_types_controller_spec.rb

This modifies the response of /ResourceTypes as described in the RFC here: https://datatracker.ietf.org/doc/html/rfc7644#section-3.4.2
I described the problem in more detail in https://github.com/RIPAGlobal/scimitar/issues/146

Modify response of ResourceTypes endpoint

---

app/controllers/scimitar/application_controller.rb

Hi, thank you very much for awesome gem.
I'm developing SCIM feature with your gem in my company.
I would like you to move the inclusion of `application_controller_mixin` to the bottom of the controller to allow to override the error handler methods or some other methods.
Or I would like you to create a new option to customize error handling.
This PR is for 1st suggestion.
If the inclusion of `application_controller_mixin` is before the method definitions, the methods defined in mixin are overridden by the methods originally defined in `Scimitar::ApplicationController`.
https://github.com/RIPAGlobal/scimitar/blob/9b4899c1fa0904ba8f6852ac49cccdb9fc23dd0c/app/controllers/scimitar/application_controller.rb#L12-L14
This prevents overriding the controller's method with the mixin. This may be …

Move the inclusion of mixin to the bottom of the controller for customizable error handling

---

app/controllers/scimitar/service_provider_configurations_controller.rb
spec/controllers/scimitar/service_provider_configurations_controller_spec.rb

This PR remove the `uses_defaults` attribute when return the JSON at the `/ServiceProviderConfig`. The response is now according to the schema as defined in https://datatracker.ietf.org/doc/html/rfc7643#section-5.
Find the discussion at https://github.com/RIPAGlobal/scimitar/issues/144.

Remove uses_defaults from ServiceProviderConfig endpoint

---

app/models/scimitar/lists/query_parser.rb
spec/models/scimitar/lists/query_parser_spec.rb

This PR adds support for [Mongoid](https://github.com/mongodb/mongoid) ("ActiveRecord for Mongo") queries to QueryParser.
The method is built based on the existing parser logic and uses a `QueryParser#tree` to form a query.
Having the filter `userType eq "Employee" and (emails eq "a@b.com" or emails eq "a@b.org")`, calling `parser.to_mongoid_query` will return
```rb
{
"$and" => [
{ :user_type => { "$eq" => 'Employee' } },
{ "$or" => [
{ :emails => { "$eq" => "a@b.com" } },
{ :emails => { "$eq" => "a@b.org" } }
]
]
}
```
The query can then be used with any scope, e.g.
```rb
scim_filter_query = parser.to_mongoid_query
User.where(organization_id: @organization.id).where(scim_filter_query)
```

Add Mongoid queries support for QueryParser

---

app/controllers/scimitar/application_controller.rb
app/models/scimitar/engine_configuration.rb
scimitar.gemspec
spec/apps/dummy/config/initializers/warden.rb
spec/controllers/scimitar/application_controller_spec.rb
spec/spec_helper.rb

Add support for fully custom authentication

---

CHANGELOG.md
README.md
app/controllers/scimitar/application_controller.rb
config/initializers/scimitar.rb
lib/scimitar/version.rb
spec/controllers/scimitar/application_controller_spec.rb

v2.12.0, with documentation
